server:
  port: 8084
  
  
spring:
  application:
    name: API-GATEWAY
 
        
  cloud:
    gateway:
      mvc:
        routes:
        - id: USERSERVICES
          uri: lb://USERSERVICES
          predicates:
            - Path=/users/** 
             
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**
          
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**